{% set name = "pbr" %}
{% set version = "7.0.0" %}
{% set bundle = "tar.gz" %}
{% set hash = "cf4127298723dafbce3afd13775ccf3885be5d3c8435751b867f9a6a10b71a39" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash }}

build:
  noarch: python
  number: 0
  preserve_egg_dir: true
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - pbr = pbr.cmd.main:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools

  run:
    - python >={{ python_min }}
    - pip
    - setuptools

test:
  imports:
    - pbr
    - pbr.cmd
    - pbr.hooks

  requires:
    - pip
    - python {{ python_min }}

  commands:
    - pip check
    - pbr --help

about:
  home: https://launchpad.net/pbr
  license_file: LICENSE
  license: Apache-2.0
  license_family: Apache
  summary: Python Build Reasonableness
  doc_url: https://docs.openstack.org/developer/pbr/
  dev_url: https://git.openstack.org/cgit/openstack-dev/pbr

extra:
  recipe-maintainers:
    - jakirkham
    - tschoonj
